name: SHINN TEST KEYS

on:
  schedule:
    # GitHub Actions sử dụng UTC
    #
    # 00:00 UTC = 07:00 Việt Nam
    # 05:00 UTC = 12:00 Việt Nam
    # 10:00 UTC = 17:00 Việt Nam
    # 15:00 UTC = 22:00 Việt Nam
    #
    - cron: "0 0,5,10,15 * * *"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  send:
    name: Create and Send Keys
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python bot.py